### ISSUE TITLE
Incorrect parsing of parameter names if space is present.

### ISSUE THREAD

**Issue by watronfire** [Wytamma/beastiary#29]
I found that if spaces are present in a parameter name, the name will be split and the additional words will be used to label the subsequent parameters.

In the attached log file and screenshot, the parameter "Current Tree" is split by Beastiary, with "Current" labelling the correct column and "Tree" labeling the adjacent column (which should be "Location.rates.California.NewYork"). All of the data in the log file is present, but the labels are incorrect from that point on.

<img width="1701" alt="image" src="https://user-images.githubusercontent.com/486245/234113567-257b7789-89c1-42bb-9d65-130e17ecc490.png">

[sample.log](https://github.com/Wytamma/beastiary/files/11314573/sample.log)

**Comment by Wytamma** [comment]
Hi @watronfire!

The headers are extracted from the log file by splitting on white space which I expect explains this error. I’ll add a better solution asap. Thanks for the feed back!

**Comment by Wytamma** [comment]
Solved in 441f5aa (Beastiary v1.6.0)
